//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompararExcel2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATAPJUDEntities2 : DbContext
    {
        public DATAPJUDEntities2()
            : base("name=DATAPJUDEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGAS> CARGAS { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<TITULARES> TITULARES { get; set; }
    }
}
