//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompararExcel2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS
    {
        public long IDNOTA { get; set; }
        public Nullable<long> RUTTITULAR { get; set; }
        public string NOTA { get; set; }
        public Nullable<long> IDTITULARFK { get; set; }
    
        public virtual TITULARES TITULARES { get; set; }
    }
}
