//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompararExcel2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITULARES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TITULARES()
        {
            this.CARGAS = new HashSet<CARGAS>();
            this.NOTAS = new HashSet<NOTAS>();
        }
    
        public long IDTITULAR { get; set; }
        public Nullable<long> RUT { get; set; }
        public string DV { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRES { get; set; }
        public string SEXO { get; set; }
        public string FECHANACIMIENTO { get; set; }
        public string TIPOSOCIO { get; set; }
        public string FECHAINGRESO { get; set; }
        public string CALJURIDICA { get; set; }
        public string CORTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string TRIBUNAL { get; set; }
        public string DESCRIPCION2 { get; set; }
        public string TIPOCUENTA { get; set; }
        public string BANCO { get; set; }
        public string NCUENTA { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public string COMUNA { get; set; }
        public string LOCALIDAD { get; set; }
        public string REGION { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string BLOCK { get; set; }
        public string DEPARTAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGAS> CARGAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
    }
}
